name: Update GitHub Activity
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Fetch latest GitHub activity
        run: |
          curl -H "Authorization: token ${{ secrets.GH_ACTIVITY_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/users/johnnylieu/events?per_page=20" \
          | jq '[.[] | {type, repo: .repo.name, created_at, url: .repo.url}]' \
          > github-activity.json

      - name: Push to Public Repo
        run: |
          git clone https://johnnylieu:${{ secrets.GH_ACTIVITY_TOKEN }}@github.com/johnnylieu/github-activity.git
          cp github-activity.json github-activity/github-activity.json
          cd github-activity
          git config --global user.email "johnnylieu@users.noreply.github.com"
          git config --global user.name "johnnylieu"
          git add github-activity.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Updated GitHub activity feed"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Commit activity file to this repo
        run: |
          git config --global user.email "johnnylieu@users.noreply.github.com"
          git config --global user.name "johnnylieu"
          git remote set-url origin https://johnnylieu:${{ secrets.GH_ACTIVITY_TOKEN }}@github.com/johnnylieu/about_me_website.git
          git add github-activity.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Updated GitHub activity feed"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit"
          fi
